"""Validate CO2 2D property tables against direct CoolProp calls.

The validator reads Fluent-style CSV tables generated by CO2_property_2Dtable.py,
performs bilinear interpolation at random pressure-temperature points, compares
the interpolated values with direct CoolProp PropsSI values, and writes error
statistics plus diagnostic figures.

Pressure in the CSV table is expected to be MPa in the first column.  CoolProp
queries use Pa internally.
"""

from __future__ import annotations

import argparse
import bisect
import csv
import math
import random
import statistics
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from CoolProp.CoolProp import PropsSI


DEFAULT_TABLE_DIR = Path(".")
DEFAULT_OUTPUT_DIR = Path("validation_results")
DEFAULT_FLUID = "CO2"
DEFAULT_SAMPLES = 1000
DEFAULT_SEED = 20260630
DEFAULT_CRITICAL_SAMPLES = 300
DEFAULT_CRITICAL_T_MIN = 300.0
DEFAULT_CRITICAL_T_MAX = 310.0
DEFAULT_CRITICAL_P_MIN = 7.0e6
DEFAULT_CRITICAL_P_MAX = 8.0e6


PROPERTY_CONFIG = {
    "density": {
        "file": "co2_density.csv",
        "coolprop_key": "D",
        "unit": "kg/m3",
    },
    "viscosity": {
        "file": "co2_viscosity.csv",
        "coolprop_key": "V",
        "unit": "Pa s",
    },
    "cp": {
        "file": "co2_cp.csv",
        "coolprop_key": "C",
        "unit": "J/(kg K)",
    },
    "conductivity": {
        "file": "co2_conductivity.csv",
        "coolprop_key": "L",
        "unit": "W/(m K)",
    },
}


@dataclass(frozen=True)
class PropertyTable:
    name: str
    temperatures: list[float]
    pressures_mpa: list[float]
    values: list[list[float]]


@dataclass(frozen=True)
class ValidationConfig:
    table_dir: Path
    output_dir: Path
    fluid: str
    samples: int
    seed: int
    critical_samples: int
    critical_t_min: float
    critical_t_max: float
    critical_p_min: float
    critical_p_max: float


def parse_float(value: str) -> float:
    stripped = value.strip()
    if stripped.lower() in {"nan", ""}:
        return math.nan
    return float(stripped)


def load_property_table(table_dir: Path, property_name: str) -> PropertyTable:
    config = PROPERTY_CONFIG[property_name]
    path = table_dir / config["file"]
    if not path.exists():
        raise FileNotFoundError(f"Missing table file: {path}")

    with path.open("r", newline="", encoding="utf-8") as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader)
        if len(header) < 3:
            raise ValueError(f"Invalid header in {path}")

        temperatures = [float(item) for item in header[1:]]
        pressures_mpa: list[float] = []
        values: list[list[float]] = []

        for row in reader:
            if not row:
                continue
            pressures_mpa.append(float(row[0]))
            values.append([parse_float(item) for item in row[1:]])

    if len(pressures_mpa) < 2 or len(temperatures) < 2:
        raise ValueError(f"Table must have at least 2 pressure rows and 2 temperature columns: {path}")

    return PropertyTable(
        name=property_name,
        temperatures=temperatures,
        pressures_mpa=pressures_mpa,
        values=values,
    )


def find_bracket(axis: list[float], value: float) -> tuple[int, int]:
    if value < axis[0] or value > axis[-1]:
        raise ValueError(f"value {value} is outside axis range {axis[0]}-{axis[-1]}")

    if value == axis[-1]:
        return len(axis) - 2, len(axis) - 1

    upper = bisect.bisect_right(axis, value)
    lower = max(0, upper - 1)
    upper = min(upper, len(axis) - 1)
    if lower == upper:
        upper += 1
    return lower, upper


def bilinear_interpolate(table: PropertyTable, pressure_pa: float, temperature_k: float) -> float:
    pressure_mpa = pressure_pa / 1.0e6
    pi0, pi1 = find_bracket(table.pressures_mpa, pressure_mpa)
    ti0, ti1 = find_bracket(table.temperatures, temperature_k)

    p0 = table.pressures_mpa[pi0]
    p1 = table.pressures_mpa[pi1]
    t0 = table.temperatures[ti0]
    t1 = table.temperatures[ti1]

    q00 = table.values[pi0][ti0]
    q01 = table.values[pi0][ti1]
    q10 = table.values[pi1][ti0]
    q11 = table.values[pi1][ti1]

    if any(math.isnan(value) for value in (q00, q01, q10, q11)):
        return math.nan

    wp = 0.0 if p1 == p0 else (pressure_mpa - p0) / (p1 - p0)
    wt = 0.0 if t1 == t0 else (temperature_k - t0) / (t1 - t0)

    return (
        (1.0 - wp) * (1.0 - wt) * q00
        + (1.0 - wp) * wt * q01
        + wp * (1.0 - wt) * q10
        + wp * wt * q11
    )


def table_domain(tables: dict[str, PropertyTable]) -> tuple[float, float, float, float]:
    first_table = next(iter(tables.values()))
    t_min = first_table.temperatures[0]
    t_max = first_table.temperatures[-1]
    p_min = first_table.pressures_mpa[0] * 1.0e6
    p_max = first_table.pressures_mpa[-1] * 1.0e6
    return t_min, t_max, p_min, p_max


def random_points(
    rng: random.Random,
    count: int,
    t_min: float,
    t_max: float,
    p_min: float,
    p_max: float,
    label: str,
) -> list[tuple[float, float, str]]:
    return [
        (
            rng.uniform(t_min, t_max),
            rng.uniform(p_min, p_max),
            label,
        )
        for _ in range(count)
    ]


def clipped_interval(start: float, stop: float, lower: float, upper: float) -> tuple[float, float] | None:
    clipped_start = max(start, lower)
    clipped_stop = min(stop, upper)
    if clipped_stop <= clipped_start:
        return None
    return clipped_start, clipped_stop


def build_validation_points(config: ValidationConfig, tables: dict[str, PropertyTable]) -> list[tuple[float, float, str]]:
    t_min, t_max, p_min, p_max = table_domain(tables)
    rng = random.Random(config.seed)
    points = random_points(rng, config.samples, t_min, t_max, p_min, p_max, "global")

    t_clip = clipped_interval(config.critical_t_min, config.critical_t_max, t_min, t_max)
    p_clip = clipped_interval(config.critical_p_min, config.critical_p_max, p_min, p_max)
    if t_clip and p_clip and config.critical_samples > 0:
        points.extend(
            random_points(
                rng,
                config.critical_samples,
                t_clip[0],
                t_clip[1],
                p_clip[0],
                p_clip[1],
                "critical",
            )
        )

    return points


def relative_error(interpolated: float, reference: float) -> float:
    if math.isnan(interpolated) or math.isnan(reference):
        return math.nan
    if reference == 0:
        return math.nan
    return abs((interpolated - reference) / reference)


def percentile(values: list[float], q: float) -> float:
    clean = sorted(value for value in values if not math.isnan(value))
    if not clean:
        return math.nan
    if len(clean) == 1:
        return clean[0]

    position = (len(clean) - 1) * q
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return clean[int(position)]
    weight = position - lower
    return clean[lower] * (1.0 - weight) + clean[upper] * weight


def summarize_errors(rows: list[dict[str, float | str]]) -> list[dict[str, float | str]]:
    summaries: list[dict[str, float | str]] = []
    properties = sorted({str(row["property"]) for row in rows})

    for property_name in properties:
        property_rows = [row for row in rows if row["property"] == property_name]
        for region in ("all", "global", "critical"):
            if region == "all":
                region_rows = property_rows
            else:
                region_rows = [row for row in property_rows if row["region"] == region]

            rel_errors = [float(row["relative_error"]) for row in region_rows if not math.isnan(float(row["relative_error"]))]
            abs_errors = [float(row["absolute_error"]) for row in region_rows if not math.isnan(float(row["absolute_error"]))]
            summaries.append(
                {
                    "property": property_name,
                    "region": region,
                    "valid_points": len(rel_errors),
                    "mean_relative_error": statistics.fmean(rel_errors) if rel_errors else math.nan,
                    "median_relative_error": statistics.median(rel_errors) if rel_errors else math.nan,
                    "p95_relative_error": percentile(rel_errors, 0.95),
                    "max_relative_error": max(rel_errors) if rel_errors else math.nan,
                    "mean_absolute_error": statistics.fmean(abs_errors) if abs_errors else math.nan,
                    "max_absolute_error": max(abs_errors) if abs_errors else math.nan,
                }
            )

    return summaries


def validate_tables(config: ValidationConfig) -> tuple[list[dict[str, float | str]], list[dict[str, float | str]]]:
    tables = {
        property_name: load_property_table(config.table_dir, property_name)
        for property_name in PROPERTY_CONFIG
    }
    points = build_validation_points(config, tables)
    rows: list[dict[str, float | str]] = []
    coolprop_failures = 0
    nan_interpolations = 0

    for temperature_k, pressure_pa, region in points:
        for property_name, table in tables.items():
            key = PROPERTY_CONFIG[property_name]["coolprop_key"]
            try:
                reference = PropsSI(key, "T", temperature_k, "P", pressure_pa, config.fluid)
            except Exception:
                coolprop_failures += 1
                continue

            interpolated = bilinear_interpolate(table, pressure_pa, temperature_k)
            if math.isnan(interpolated):
                nan_interpolations += 1
                continue

            abs_error = abs(interpolated - reference)
            rel_error = relative_error(interpolated, reference)
            rows.append(
                {
                    "property": property_name,
                    "region": region,
                    "temperature_K": temperature_k,
                    "pressure_MPa": pressure_pa / 1.0e6,
                    "coolprop_value": reference,
                    "table_interp_value": interpolated,
                    "absolute_error": abs_error,
                    "relative_error": rel_error,
                }
            )

    summaries = summarize_errors(rows)
    print(f"Validated points: {len(rows)} property samples")
    print(f"CoolProp failures skipped: {coolprop_failures}")
    print(f"NaN interpolations skipped: {nan_interpolations}")
    return rows, summaries


def write_dict_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def require_matplotlib():
    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise SystemExit(
            "matplotlib is required for figures. Install it with: pip install matplotlib"
        ) from exc
    return plt


def plot_error_boxplot(output_dir: Path, rows: list[dict[str, float | str]]) -> None:
    plt = require_matplotlib()
    properties = list(PROPERTY_CONFIG.keys())
    data = [
        [
            float(row["relative_error"]) * 100.0
            for row in rows
            if row["property"] == property_name and not math.isnan(float(row["relative_error"]))
        ]
        for property_name in properties
    ]

    fig, ax = plt.subplots(figsize=(8, 4.8))
    ax.boxplot(data, labels=properties, showfliers=False)
    ax.set_yscale("log")
    ax.set_ylabel("Relative error / %")
    ax.set_title("CSV bilinear interpolation error vs CoolProp")
    ax.grid(True, which="both", alpha=0.3)
    fig.tight_layout()
    fig.savefig(output_dir / "relative_error_boxplot.png", dpi=300)
    plt.close(fig)


def plot_error_vs_temperature(output_dir: Path, rows: list[dict[str, float | str]]) -> None:
    plt = require_matplotlib()
    properties = list(PROPERTY_CONFIG.keys())

    fig, axes = plt.subplots(2, 2, figsize=(10, 7), sharex=True)
    for ax, property_name in zip(axes.ravel(), properties):
        property_rows = [row for row in rows if row["property"] == property_name]
        colors = ["tab:red" if row["region"] == "critical" else "tab:blue" for row in property_rows]
        ax.scatter(
            [float(row["temperature_K"]) for row in property_rows],
            [float(row["relative_error"]) * 100.0 for row in property_rows],
            s=8,
            alpha=0.55,
            c=colors,
            linewidths=0,
        )
        ax.set_yscale("log")
        ax.set_title(property_name)
        ax.grid(True, which="both", alpha=0.3)

    for ax in axes[-1]:
        ax.set_xlabel("Temperature / K")
    for ax in axes[:, 0]:
        ax.set_ylabel("Relative error / %")

    fig.suptitle("Interpolation relative error vs temperature")
    fig.tight_layout()
    fig.savefig(output_dir / "relative_error_vs_temperature.png", dpi=300)
    plt.close(fig)


def plot_error_vs_pressure(output_dir: Path, rows: list[dict[str, float | str]]) -> None:
    plt = require_matplotlib()
    properties = list(PROPERTY_CONFIG.keys())

    fig, axes = plt.subplots(2, 2, figsize=(10, 7), sharex=True)
    for ax, property_name in zip(axes.ravel(), properties):
        property_rows = [row for row in rows if row["property"] == property_name]
        colors = ["tab:red" if row["region"] == "critical" else "tab:blue" for row in property_rows]
        ax.scatter(
            [float(row["pressure_MPa"]) for row in property_rows],
            [float(row["relative_error"]) * 100.0 for row in property_rows],
            s=8,
            alpha=0.55,
            c=colors,
            linewidths=0,
        )
        ax.set_yscale("log")
        ax.set_title(property_name)
        ax.grid(True, which="both", alpha=0.3)

    for ax in axes[-1]:
        ax.set_xlabel("Pressure / MPa")
    for ax in axes[:, 0]:
        ax.set_ylabel("Relative error / %")

    fig.suptitle("Interpolation relative error vs pressure")
    fig.tight_layout()
    fig.savefig(output_dir / "relative_error_vs_pressure.png", dpi=300)
    plt.close(fig)


def plot_critical_profile(config: ValidationConfig, output_dir: Path) -> None:
    plt = require_matplotlib()
    tables = {
        property_name: load_property_table(config.table_dir, property_name)
        for property_name in PROPERTY_CONFIG
    }
    t_min, t_max, p_min, p_max = table_domain(tables)
    temperature_start = max(config.critical_t_min, t_min)
    temperature_stop = min(config.critical_t_max, t_max)
    pressure_pa = min(max(7.377298373446752e6, p_min), p_max)

    if temperature_stop <= temperature_start:
        return

    temperatures = [
        temperature_start + i * (temperature_stop - temperature_start) / 200
        for i in range(201)
    ]

    fig, axes = plt.subplots(2, 2, figsize=(10, 7), sharex=True)
    for ax, property_name in zip(axes.ravel(), PROPERTY_CONFIG.keys()):
        table = tables[property_name]
        key = PROPERTY_CONFIG[property_name]["coolprop_key"]
        cp_values: list[float] = []
        interp_values: list[float] = []

        for temperature in temperatures:
            try:
                cp_values.append(PropsSI(key, "T", temperature, "P", pressure_pa, config.fluid))
            except Exception:
                cp_values.append(math.nan)
            interp_values.append(bilinear_interpolate(table, pressure_pa, temperature))

        ax.plot(temperatures, cp_values, label="CoolProp", linewidth=1.5)
        ax.plot(temperatures, interp_values, label="CSV interpolation", linestyle="--", linewidth=1.2)
        ax.set_title(property_name)
        ax.grid(True, alpha=0.3)

    for ax in axes[-1]:
        ax.set_xlabel("Temperature / K")
    for ax in axes[:, 0]:
        ax.set_ylabel("Property value")
    axes[0, 0].legend()
    fig.suptitle(f"Critical-region profile at P = {pressure_pa / 1.0e6:.3f} MPa")
    fig.tight_layout()
    fig.savefig(output_dir / "critical_region_profile.png", dpi=300)
    plt.close(fig)


def write_report(config: ValidationConfig, summaries: list[dict[str, float | str]], output_dir: Path) -> None:
    lines = [
        "# CO2 2D Table Validation Report",
        "",
        f"- Table directory: `{config.table_dir}`",
        f"- Fluid: `{config.fluid}`",
        f"- Global random samples: `{config.samples}`",
        f"- Critical-region random samples: `{config.critical_samples}`",
        f"- Critical region: `{config.critical_t_min}-{config.critical_t_max} K`, "
        f"`{config.critical_p_min / 1.0e6}-{config.critical_p_max / 1.0e6} MPa`",
        "",
        "## Error Summary",
        "",
        "| Property | Region | Valid points | Mean rel. error | P95 rel. error | Max rel. error |",
        "|---|---:|---:|---:|---:|---:|",
    ]

    for row in summaries:
        lines.append(
            f"| {row['property']} | {row['region']} | {row['valid_points']} | "
            f"{float(row['mean_relative_error']):.6e} | "
            f"{float(row['p95_relative_error']):.6e} | "
            f"{float(row['max_relative_error']):.6e} |"
        )

    lines.extend(
        [
            "",
            "## Figures",
            "",
            "- `relative_error_boxplot.png`",
            "- `relative_error_vs_temperature.png`",
            "- `relative_error_vs_pressure.png`",
            "- `critical_region_profile.png`",
            "",
            "Relative errors are dimensionless in the CSV summaries. Figure axes show relative error in percent.",
        ]
    )

    (output_dir / "validation_report.md").write_text("\n".join(lines), encoding="utf-8")


def run_validation(config: ValidationConfig) -> None:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    rows, summaries = validate_tables(config)
    write_dict_csv(config.output_dir / "validation_point_errors.csv", rows)
    write_dict_csv(config.output_dir / "validation_error_summary.csv", summaries)
    write_report(config, summaries, config.output_dir)

    if rows:
        plot_error_boxplot(config.output_dir, rows)
        plot_error_vs_temperature(config.output_dir, rows)
        plot_error_vs_pressure(config.output_dir, rows)
        plot_critical_profile(config, config.output_dir)

    print(f"Validation outputs saved to {config.output_dir}")


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("value must be a positive integer")
    return parsed


def parse_args() -> ValidationConfig:
    parser = argparse.ArgumentParser(
        description="Validate CO2 2D CSV property tables against direct CoolProp calls."
    )
    parser.add_argument("--table-dir", type=Path, default=DEFAULT_TABLE_DIR, help="Directory containing CO2 CSV tables")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Directory for validation outputs")
    parser.add_argument("--fluid", default=DEFAULT_FLUID, help=f"CoolProp fluid name. Default: {DEFAULT_FLUID}")
    parser.add_argument("--samples", type=positive_int, default=DEFAULT_SAMPLES, help="Global random validation points")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Random seed")
    parser.add_argument(
        "--critical-samples",
        type=int,
        default=DEFAULT_CRITICAL_SAMPLES,
        help="Random validation points in the critical region; use 0 to disable",
    )
    parser.add_argument("--critical-t-min", type=float, default=DEFAULT_CRITICAL_T_MIN, help="Critical minimum T, K")
    parser.add_argument("--critical-t-max", type=float, default=DEFAULT_CRITICAL_T_MAX, help="Critical maximum T, K")
    parser.add_argument("--critical-p-min", type=float, default=DEFAULT_CRITICAL_P_MIN, help="Critical minimum P, Pa")
    parser.add_argument("--critical-p-max", type=float, default=DEFAULT_CRITICAL_P_MAX, help="Critical maximum P, Pa")

    args = parser.parse_args()
    if args.critical_samples < 0:
        raise SystemExit("--critical-samples must be non-negative")

    return ValidationConfig(
        table_dir=args.table_dir,
        output_dir=args.output_dir,
        fluid=args.fluid,
        samples=args.samples,
        seed=args.seed,
        critical_samples=args.critical_samples,
        critical_t_min=args.critical_t_min,
        critical_t_max=args.critical_t_max,
        critical_p_min=args.critical_p_min,
        critical_p_max=args.critical_p_max,
    )


if __name__ == "__main__":
    run_validation(parse_args())
